# action.yml
name: 'idealtex-assistant'
description: 'Idealtex-tools'
inputs:
  NEW_VERSION:  
    description: 'version of service'
  SERVICE_NAME:  
    description: 'name of service'
    required: true
secrets:
  GITHUB_TOKEN:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    NEW_VERSION: ${{ inputs.NEW_VERSION }}
    SERVICE_NAME: ${{ inputs.SERVICE_NAME }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}