name: release

on:
  workflow_call:
    secrets:
      RELEASE_TOKEN:
        required: true
  workflow_dispatch:
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
      - name: Validation
        run: python scripts/validation.py
  tag:
    runs-on: ubuntu-latest
    needs: validation
    outputs:
      new_tag: ${{ steps.version.outputs.version }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history
    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1
      with:
        release-branch: main
    - name: Create tag
      uses: actions/github-script@v6.4.0
      with:
        github-token: ${{ secrets.RELEASE_TOKEN }}
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ steps.version.outputs.version }}',
            sha: context.sha
          })