# This is a basic workflow to help you get started with Actions

name: release

on:
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:               
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
      - name: Validation
        run: python scripts/validation.py